### ISSUE TITLE
Update image for Go 1.6

### ISSUE THREAD

**Issue by teelahti** [CenturyLinkLabs/golang-builder#22]
Currently this image uses golang:latest as base image. That image is already in Go 1.6. A rebuild of this image would give 1.6 for users, could someone do that? 

Of course even better would be to have image tags based on Go version, so that users could bind to specific Go version.

**Comment by teelahti** [comment]
Image has been re-pushed, closing.

**Comment by xjewer** [comment]
Why close the PR? Specify GOLANG version for build is a significant thing. Could you reopen issue and reword it?

**Comment by teelahti** [comment]
I agree and would really like to see versioned images. This issue was only about pushing new latest, there already is an issue #17 open  about version locking.
